sudo: required
env:
  # Fix Windows build never ending in Travis CI
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no
services:
  - docker
before_install:
  - docker build -t hoang/docker-react -f Dockerfile.dev .

script:
  - docker run hoang/docker-react npm run test -- --coverage
