sudo: required
env:
  - YARN_GPG=no
services:
  - docker
before_install:
  - docker build -t hoang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hoang/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-063889144830"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
