version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/mode_modules
      - .:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/mode_modules
      - .:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: ["npm", "run", "-e CI=true", "test"]
